version: 2

jobs:
  
  build:
    machine: true
    steps:
      - checkout
      - run: sleep 10
      - run: echo "hello!"

  # test:
  #   docker:
  #     - image: circleci/node:6
  #   steps:
  #     - run: sleep 10
  #     - run: echo "goodbye!"

  # test2:
  #   docker:
  #     - image: circleci/node:6
  #   steps:
  #     - run: sleep 10
  #     - run: echo "goodbye!"

  # test3:
  #   docker:
  #     - image: circleci/node:6
  #   steps:
  #     - run: sleep 10
  #     - run: echo "goodbye!"

  # test4:
  #   docker:
  #     - image: circleci/node:6
  #   steps:
  #     - run: sleep 10
  #     - run: echo "goodbye!"

#   download_artifacts:
#     docker:
#       - image: circleci/ruby:2.8
#     steps:
#       - run: echo "downloaded artifacts"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
      # - test2
      # - test3
      # - test4

